version: '3.1'
services:
  flask-web:
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DB: tc_store_new
      MONGO_HOST: mongodb
      MONGO_DB: cocoa
    ports:
      - 8081:8080
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./db_storage/mysql/data:/var/lib/mysql
    ports:
      - 3308:3306
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./db_storage/mongodb/data:/data/db
    ports:
      - 27018:27017